# Generated by Django 3.1.2 on 2020-11-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedata',
            name='knowledge_data_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
