# Generated by Django 3.1.2 on 2020-11-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0002_auto_20201101_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedquestion',
            name='generated_question_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='generated question id'),
        ),
        migrations.AlterField(
            model_name='knowledgedatarefercencedocumentlink',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='knowledgedatasynonymlink',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='question id'),
        ),
        migrations.AlterField(
            model_name='responsedata',
            name='response_data_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='response data id'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='subject id'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='verb_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='verb id'),
        ),
        migrations.AlterUniqueTogether(
            name='responsedata',
            unique_together={('knowledge_data', 'type')},
        ),
    ]
