# Generated by Django 3.1.2 on 2020-11-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0003_auto_20201101_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedatasynonymlink',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
