# Generated by Django 3.1.2 on 2020-11-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0004_auto_20201101_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='verbs',
            field=models.TextField(null=True, verbose_name='verbs belong to the subject'),
        ),
    ]
