# Generated by Django 3.1.2 on 2020-11-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0005_subject_verbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='type',
            field=models.IntegerField(choices=[(1, 'System'), (2, 'NLP')], default=1, verbose_name='setting type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsedata',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'what'), (2, 'when'), (3, 'where'), (4, 'who'), (5, 'why'), (6, 'how'), (7, 'yesno')], verbose_name='type of question'),
        ),
        migrations.DeleteModel(
            name='Verb',
        ),
    ]
