# Generated by Django 3.1.2 on 2020-11-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0006_auto_20201106_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='train data file name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.IntegerField(choices=[(1, 'Available'), (2, 'Disable'), (3, 'Deleted')], verbose_name='Available status')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='file created time')),
                ('mdate', models.DateTimeField(auto_now=True, verbose_name='details modified time')),
            ],
            options={
                'db_table': 'train_data',
            },
        ),
    ]
