# Generated by Django 3.1.2 on 2020-11-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0007_traindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='traindata',
            name='delete_reason',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='traindata',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
