# Generated by Django 3.1.2 on 2020-11-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0008_auto_20201109_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, 'what'), (2, 'when'), (3, 'where'), (4, 'who'), (5, 'why'), (6, 'how'), (7, 'yesno')], default=1, verbose_name='question type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traindata',
            name='include_data',
            field=models.TextField(null=True, verbose_name='Excluded knowledge datas'),
        ),
    ]
