# Generated by Django 3.1.2 on 2020-11-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0009_auto_20201109_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(max_length=13, verbose_name='question type'),
        ),
    ]
