# Generated by Django 3.1.2 on 2020-11-13 01:31

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0010_auto_20201109_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='chat_history_id',
            new_name='log_id',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='cdate',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='session_end',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='chat session end time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chathistory',
            name='session_start',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='chat session start time'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='log',
            field=models.BinaryField(blank=True, verbose_name='chat history'),
        ),
    ]
