# Generated by Django 3.1.2 on 2020-11-13 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0011_auto_20201113_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('chat_session_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='log id')),
                ('sent_from', models.SmallIntegerField(choices=[(1, 'User'), (2, 'Chatbot')])),
                ('message', models.TextField(null=True, verbose_name='chat message')),
                ('intent', models.TextField(null=True, verbose_name='predicted intent name')),
                ('question_types', models.TextField(null=True, verbose_name='predicted question types')),
                ('action', models.SmallIntegerField(choices=[(0, 'initial'), (1, 'answer'), (2, 'await'), (3, 'ok'), (4, 'ng')], null=True, verbose_name='chatbot reaction to user')),
                ('recorded_time', models.DateTimeField(verbose_name='message send time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='chat user id')),
            ],
            options={
                'db_table': 'chat_session',
            },
        ),
    ]
