# Generated by Django 3.1.2 on 2020-11-16 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0013_auto_20201113_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='chat_id',
            new_name='log',
        ),
        migrations.RemoveField(
            model_name='message',
            name='question_types',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='data_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vhcm.traindata', verbose_name='chatbot data version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='data_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vhcm.traindata', verbose_name='chatbot data version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='question_type',
            field=models.SmallIntegerField(choices=[(1, 'what'), (2, 'when'), (3, 'where'), (4, 'who'), (5, 'why'), (6, 'how'), (7, 'yesno')], null=True, verbose_name='predicted question types'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='session_start',
            field=models.DateTimeField(verbose_name='chat session start time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recorded_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='message send time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_from',
            field=models.SmallIntegerField(choices=[(1, 'User'), (2, 'Bot')]),
        ),
    ]
