# Generated by Django 3.1.2 on 2020-11-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0014_auto_20201116_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='setting_name',
            field=models.CharField(max_length=100, verbose_name='setting name'),
        ),
    ]
