# Generated by Django 3.1.2 on 2020-11-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0015_auto_20201118_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='question_type',
            field=models.CharField(max_length=20, null=True, verbose_name='predicted question types'),
        ),
    ]
