# Generated by Django 3.1.2 on 2020-11-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0017_comment_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='edited status'),
        ),
    ]
