# Generated by Django 3.1.2 on 2020-11-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0018_comment_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='type',
            field=models.IntegerField(choices=[(1, 'System'), (2, 'NLP'), (3, 'Review process')], verbose_name='setting type'),
        ),
    ]
