# Generated by Django 3.1.2 on 2020-11-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0020_user_avatar2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar2',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatar/', verbose_name='user avatar'),
        ),
    ]
