# Generated by Django 3.1.2 on 2020-11-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0021_auto_20201122_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
