# Generated by Django 3.1.2 on 2020-11-22 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0022_remove_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar2',
            new_name='avatar',
        ),
    ]
