# Generated by Django 3.1.2 on 2020-11-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0023_auto_20201122_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='refercencedocument',
            name='cover2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='document cover'),
        ),
    ]
