# Generated by Django 3.1.2 on 2020-11-22 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0024_refercencedocument_cover2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refercencedocument',
            name='cover',
        ),
    ]
