# Generated by Django 3.1.2 on 2020-11-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0025_remove_refercencedocument_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refercencedocument',
            old_name='cover2',
            new_name='cover',
        ),
    ]
