# Generated by Django 3.1.2 on 2020-11-23 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0027_auto_20201123_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='log',
        ),
        migrations.AddField(
            model_name='report',
            name='process_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='process_user', to=settings.AUTH_USER_MODEL, verbose_name='report data process user'),
        ),
        migrations.AddField(
            model_name='report',
            name='reject_reason',
            field=models.TextField(null=True, verbose_name='reject reason'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_user', to='vhcm.user', verbose_name='reported user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Wrong answer'), (2, 'Lack of data')], verbose_name='report type'),
        ),
    ]
