# Generated by Django 3.1.2 on 2020-11-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0030_auto_20201125_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='foward_intent',
            new_name='forward_intent',
        ),
        migrations.AddField(
            model_name='report',
            name='mdate',
            field=models.DateTimeField(auto_now=True, verbose_name='report accepted/rejected date'),
        ),
    ]
