# Generated by Django 3.1.2 on 2020-11-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0031_auto_20201125_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reportable_bot_states',
            field=models.TextField(null=True, verbose_name='indexes of reportable bot states'),
        ),
    ]
