# Generated by Django 3.1.2 on 2020-12-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0032_message_reportable_bot_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_reference',
            field=models.TextField(null=True, verbose_name='report data reference'),
        ),
        migrations.AlterField(
            model_name='refercencedocument',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='reference_document/', verbose_name='document cover'),
        ),
    ]
