# Generated by Django 3.1.2 on 2020-11-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refercencedocument',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='document cover'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='type',
            field=models.IntegerField(choices=[(1, 'System'), (2, 'NLP'), (3, 'Review process')], verbose_name='setting type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatar/', verbose_name='user avatar'),
        ),
    ]
