# Generated by Django 3.1.2 on 2020-11-24 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0002_auto_20201123_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_session_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='report_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='log',
        ),
        migrations.AddField(
            model_name='message',
            name='user_question',
            field=models.TextField(null=True, verbose_name='user asked question'),
        ),
        migrations.AddField(
            model_name='report',
            name='bot_answer',
            field=models.TextField(null=True, verbose_name='bot answered content'),
        ),
        migrations.AddField(
            model_name='report',
            name='bot_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vhcm.traindata', verbose_name='bot version'),
        ),
        migrations.AddField(
            model_name='report',
            name='intent',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='intent'),
        ),
        migrations.AddField(
            model_name='report',
            name='processor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='processor', to=settings.AUTH_USER_MODEL, verbose_name='report data process user'),
        ),
        migrations.AddField(
            model_name='report',
            name='question',
            field=models.TextField(null=True, verbose_name='user asked question'),
        ),
        migrations.AddField(
            model_name='report',
            name='reject_reason',
            field=models.TextField(null=True, verbose_name='reject reason'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='vhcm.user', verbose_name='reporter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='reporter_note',
            field=models.TextField(null=True, verbose_name='reporter note'),
        ),
        migrations.AlterField(
            model_name='knowledgedata',
            name='intent',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='intent'),
        ),
        migrations.AlterField(
            model_name='knowledgedata',
            name='mdate',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified date'),
        ),
        migrations.AlterField(
            model_name='knowledgedata',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Available'), (1, 'Processing'), (2, 'Done'), (3, 'Disable')], db_index=True, default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_from',
            field=models.SmallIntegerField(choices=[(1, 'User'), (2, 'Bot'), (3, 'System')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Wrong answer'), (2, 'Contribute data')], verbose_name='report type'),
        ),
    ]
