# Generated by Django 3.1.2 on 2020-12-02 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0003_auto_20201124_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='reject_reason',
            new_name='processor_note',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='intent',
            new_name='reported_intent',
        ),
        migrations.AddField(
            model_name='message',
            name='reportable_bot_states',
            field=models.TextField(null=True, verbose_name='indexes of reportable bot states'),
        ),
        migrations.AddField(
            model_name='report',
            name='forward_intent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vhcm.knowledgedata', verbose_name='knowledge data that issue forwarded to'),
        ),
        migrations.AddField(
            model_name='report',
            name='mdate',
            field=models.DateTimeField(auto_now=True, verbose_name='report accepted/rejected date'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_reference',
            field=models.TextField(null=True, verbose_name='report data reference'),
        ),
        migrations.AlterField(
            model_name='refercencedocument',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='reference_document/', verbose_name='document cover'),
        ),
    ]
