# Generated by Django 3.1.2 on 2020-12-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0007_auto_20201208_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='default',
            field=models.TextField(null=True, verbose_name='default value'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='description',
            field=models.TextField(null=True, verbose_name='setting description'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=models.TextField(null=True, verbose_name='value'),
        ),
    ]
