# Generated by Django 3.1.2 on 2020-12-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0008_auto_20201208_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='editable',
            field=models.BooleanField(default=True, verbose_name='editable status'),
        ),
        migrations.AlterField(
            model_name='knowledgedatarefercencedocumentlink',
            name='page',
            field=models.TextField(default=None, null=True, verbose_name='document page number'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgedatarefercencedocumentlink',
            unique_together={('knowledge_data', 'reference_document')},
        ),
    ]
