# Generated by Django 3.1.2 on 2020-12-14 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0009_auto_20201213_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_seen',
            field=models.BooleanField(default=False, null=True, verbose_name='is user being replied to seen the comment?'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Processed'), (3, 'Rejected')], verbose_name='status'),
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vhcm.comment', verbose_name='base comment')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vhcm.report', verbose_name='report id')),
                ('report_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user being reported to')),
            ],
            options={
                'db_table': 'knowledge_data_comment_report',
            },
        ),
    ]
