# Generated by Django 3.1.2 on 2020-12-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0010_auto_20201214_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_seen',
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='user_seen',
            field=models.BooleanField(default=False, verbose_name='is user being replied to seen the report?'),
        ),
    ]
