# Generated by Django 3.1.2 on 2020-12-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0011_auto_20201214_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='editable',
        ),
        migrations.AddField(
            model_name='comment',
            name='able_to_delete',
            field=models.BooleanField(default=True, verbose_name='able to delete status'),
        ),
    ]
