# Generated by Django 3.1.2 on 2020-12-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0012_auto_20201214_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatstate',
            name='context_question',
            field=models.BooleanField(null=True, verbose_name='is user asking context question'),
        ),
        migrations.AddField(
            model_name='chatstate',
            name='hcm_question',
            field=models.BooleanField(null=True, verbose_name='is user asking hcm related question'),
        ),
    ]
