# Generated by Django 3.1.2 on 2020-10-17 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='user id')),
                ('username', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='username')),
                ('fullname', models.CharField(db_index=True, default='', max_length=60, verbose_name='fullname')),
                ('nationality', models.CharField(default='Vietnam', max_length=60, verbose_name='nationality')),
                ('place_of_birth', models.CharField(default='', max_length=255, verbose_name='place of birth')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, verbose_name='date of birth')),
                ('address', models.TextField(default='', verbose_name='address')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='phone number')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='account create time')),
                ('mdate', models.DateTimeField(auto_now=True, verbose_name='account modify time')),
                ('email', models.EmailField(db_index=True, max_length=60, null=True, verbose_name='email address')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Knowledge_Data',
            fields=[
                ('knowledge_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('intent', models.CharField(db_index=True, max_length=50, verbose_name='intent')),
                ('intent_fullname', models.CharField(db_index=True, max_length=255, verbose_name='intent full name')),
                ('base_response', models.TextField(verbose_name='base response')),
                ('status', models.SmallIntegerField(default=0, verbose_name='status')),
                ('raw_data', models.TextField(verbose_name='raw text data')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('mdate', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('create_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kd_create_user_id', to=settings.AUTH_USER_MODEL, verbose_name='create user')),
                ('edit_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kd_edit_user_id', to=settings.AUTH_USER_MODEL, verbose_name='edit user')),
            ],
        ),
        migrations.CreateModel(
            name='Refercence_Document',
            fields=[
                ('reference_document_id', models.AutoField(primary_key=True, serialize=False, verbose_name='reference document id')),
                ('reference_name', models.CharField(db_index=True, default='', max_length=100, verbose_name='reference name')),
                ('link', models.TextField(blank=True, verbose_name='reference urls')),
                ('cover', models.BinaryField(blank=True, verbose_name='document cover')),
                ('author', models.CharField(db_index=True, default='', max_length=50, verbose_name='document author')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('mdate', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('create_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rd_create_user_id', to=settings.AUTH_USER_MODEL, verbose_name='create user')),
                ('last_edit_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rd_last_edit_user_id', to=settings.AUTH_USER_MODEL, verbose_name='last edit user')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeData_RefercenceDocument_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField(verbose_name='document page number')),
                ('extra_info', models.TextField(verbose_name='extra info on reference document')),
                ('knowledge_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vhcm.knowledge_data')),
                ('reference_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vhcm.refercence_document')),
            ],
        ),
        migrations.AddField(
            model_name='knowledge_data',
            name='references',
            field=models.ManyToManyField(through='vhcm.KnowledgeData_RefercenceDocument_Link', to='vhcm.Refercence_Document'),
        ),
    ]
