# Generated by Django 3.1.2 on 2020-10-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refercencedocument',
            name='author',
            field=models.TextField(db_index=True, default='', verbose_name='document author'),
        ),
    ]
