# Generated by Django 3.1.2 on 2020-10-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhcm', '0002_auto_20201021_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refercencedocument',
            name='cover',
            field=models.BinaryField(null=True, verbose_name='document cover'),
        ),
    ]
